import React from 'react';
import HomeSettings from '../components/Settings/HomeSettings';
import PomodoroSettings from '../components/Settings/PomodoroSettings';
// import {makeStyles} from '@material-ui/core/styles';

/**
 * Settings
 * @desc The page that displays the UI components for settings and sends change
 * events to the Global context.
 */

let textPrimary = "#000000";
let textSecondary = "#838383";
let colorPrimary = "#086788";
let colorSecondary = "#07a0c3";
  


const BlueSwitch = withStyles({
    switchBase: {
        color: textSecondary,
        '&$checked': {
            color: colorPrimary,
        },
        '&$checked + $track': {
            backgroundColor: colorSecondary,
        },
    },
    checked: {},
    track: {},
})(Switch);

const BlueCheckbox = withStyles({
    root: {
        color: colorSecondary,
        '&$checked': {
            color: colorPrimary,
        },
    },
    checked: {},
})(Checkbox);

function Settings(props) {

    const { settings, dispatch, SettingsActions } = useSettingsGlobalState()
    
    /**
     * Receives user events from Checkbox and Switch components, and dispatches
     * setting changes to the Global state.
     * @param {Object} event - The event generated by the HTML element
     */
    const changeCheckBox = (event) => {
        let name = event.target.name;
        let newValue = event.target.checked;

        dispatch(SettingsActions.HANDLE_CHANGE(name, newValue));
    }

    /**
     * Receives user events from Select components, and dispatches
     * setting changes to the Global state.
     * @param {Object} event - The event generated by the HTML element
     */
    const changeNumberValue = (event) => {
        let name = event.target.name;
        let newValue = event.target.value;

        dispatch(SettingsActions.HANDLE_CHANGE(name, newValue));
    }

    return (
        <div className="Settings">
            <br></br>
            <hr></hr>
            <h2>General</h2>
            <PomodoroSettings/>
            <hr></hr>
            <h2>Home Screen Customization</h2>
            <HomeSettings/>
        </div>
    )
}

export default Settings;